-- not really sure what to do with this file, I guess it makes stuff happen when
-- the plugin first loads? but then why not have it in the setup function?
-- vim.api.nvim_create_user_command("MyFirstFunction", require("llmancer").hello, {})
