name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['v0.9.4', 'nightly']

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim_version }}
    
    - name: Install dependencies
      run: |
        git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
        git clone --depth 1 https://github.com/folke/neodev.nvim ~/.local/share/nvim/site/pack/vendor/start/neodev.nvim
    
    - name: Run tests
      run: make test 